# Generated by Django 4.0.1 on 2022-01-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.TextField(verbose_name='item name')),
                ('itemDesc', models.TextField(verbose_name='item description')),
                ('itemNum', models.IntegerField(default=0, verbose_name='item quantity')),
            ],
        ),
    ]
