# Generated by Django 4.0.1 on 2022-01-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='itemNum',
            new_name='numItems',
        ),
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='item name'),
        ),
    ]
